name: home_assignment
description: This app uses NewsAPI to fetch and display news around the world.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0
  dio: ^5.3.3
  hive: ^2.2.3
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.2

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
   - assets/api_key.txt
